# Introduction to Pandas Lab

Complete the following set of exercises to solidify your knowledge of Pandas fundamentals.

### 1. Import Numpy and Pandas and alias them to `np` and `pd` respectively.

In [1]:
import pandas as pd
import numpy as np

### 2. Create a Pandas Series containing the elements of the list below.

In [2]:
lst = [5.7, 75.2, 74.4, 84.0, 66.5, 66.3, 55.8, 75.7, 29.1, 43.7]

In [4]:
series_lst = pd.Series(lst)     # converts Python lst into a Pandas Series

### 3. Use indexing to return the third value in the Series above.

*Hint: Remember that indexing begins at 0.*

In [7]:
series_lst[2]      #given that indexing start from 0, we need to input index 2 to obtain the third value in the Series we created

np.float64(74.4)

### 4. Create a Pandas DataFrame from the list of lists below. Each sublist should be represented as a row.

In [9]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

In [10]:
# By using the constructor function pd.DataFrame():

df = pd.DataFrame(b)
df

      0     1     2     3     4
0  53.1  95.0  67.5  35.0  78.4
1  61.3  40.8  30.8  37.8  87.6
2  20.6  73.2  44.2  14.6  91.8
3  57.4   0.1  96.1   4.2  69.5
4  83.6  20.5  85.4  22.8  35.9
5  49.0  69.0   0.1  31.8  89.1
6  23.3  40.7  95.0  83.8  26.9
7  27.6  26.4  53.8  88.8  68.5
8  96.6  96.4  53.4  72.4  50.1
9  73.7  39.0  43.2  81.6  34.7

### 5. Rename the data frame columns based on the names in the list below.

In [12]:
b_names = ["score_1", "score_2", "score_3", "score_4", "score_5"]

#b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     #[61.3, 40.8, 30.8, 37.8, 87.6],
     #[20.6, 73.2, 44.2, 14.6, 91.8],
     #[57.4, 0.1, 96.1, 4.2, 69.5],
     #[83.6, 20.5, 85.4, 22.8, 35.9],
     #[49.0, 69.0, 0.1, 31.8, 89.1],
     #[23.3, 40.7, 95.0, 83.8, 26.9],
     #[27.6, 26.4, 53.8, 88.8, 68.5],
     #[96.6, 96.4, 53.4, 72.4, 50.1],
     #[73.7, 39.0, 43.2, 81.6, 34.7]]

In [ ]:
df = pd.DataFrame(b, columns=b_names)   #renaming columns in original data frame b to the elements contained in the list "b_names"

df.columns = [col.lower().replace(" ", "_") for col in df.columns]   # list comprehension for setting column names to lowercase and any whitespace replaced with underscores.

print(df.columns)    # printing renamed columns

Index(['score_1', 'score_2', 'score_3', 'score_4', 'score_5'], dtype='object')

In [ ]:
df   # re-printing df with renamed columns

   score_1  score_2  score_3  score_4  score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

### 6. Create a subset of this data frame that contains only the Score 1, 3, and 5 columns.

In [ ]:
subset_scores = df[['score_1', 'score_3', 'score_5']]  # accessing the specified columns of the dataframe and assigning these to a subset

subset_scores

   score_1  score_3  score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

### 7. From the original data frame, calculate the average Score_3 value.

In [10]:
# your code here

### 8. From the original data frame, calculate the maximum Score_4 value.

In [11]:
# your code here

### 9. From the original data frame, calculate the median Score 2 value.

In [12]:
# your code here

### 10. Create a Pandas DataFrame from the dictionary of product orders below.

In [13]:
orders = {'Description': ['LUNCH BAG APPLE DESIGN',
  'SET OF 60 VINTAGE LEAF CAKE CASES ',
  'RIBBON REEL STRIPES DESIGN ',
  'WORLD WAR 2 GLIDERS ASSTD DESIGNS',
  'PLAYING CARDS JUBILEE UNION JACK',
  'POPCORN HOLDER',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'PARTY BUNTING',
  'JAZZ HEARTS ADDRESS BOOK',
  'SET OF 4 SANTA PLACE SETTINGS'],
 'Quantity': [1, 24, 1, 2880, 2, 7, 1, 4, 10, 48],
 'UnitPrice': [1.65, 0.55, 1.65, 0.18, 1.25, 0.85, 11.95, 4.95, 0.19, 1.25],
 'Revenue': [1.65, 13.2, 1.65, 518.4, 2.5, 5.95, 11.95, 19.8, 1.9, 60.0]}

In [14]:
# your code here

### 11. Calculate the total quantity ordered and revenue generated from these orders.

In [15]:
# your code here

### 12. Obtain the prices of the most expensive and least expensive items ordered and print the difference.

In [16]:
# your code here

## Let's load another dataset for more exercisesº

In [17]:
# Run this code:
admissions = pd.read_csv('../Admission_Predict.csv')

Let's evaluate the dataset by looking at the `head` function.

In [18]:
# your code here

### 1 - Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [19]:
# your code here

###  2 -  Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [20]:
# your code here

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

### 3 - In this part of the lab, we would like to test complex conditions on the entire data set at once. Let's start by finding the number of rows where the CGPA is greater than 9 and the student has performed an investigation.

In [21]:
# your code here

### 4 - Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [22]:
# your code here